services:
  postgres:
    image: postgres:16
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-net

  tg-bot:
    build:
      context: ./tg-bot
      dockerfile: Dockerfile
    container_name: tg-bot
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - tg_bot_logs:/app/logs
    networks:
      - app-net

  django-admin:
    build:
      context: ./django-admin
      dockerfile: Dockerfile
    container_name: django-admin
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - tg-bot
    restart: on-failure
    volumes:
      - static_volume:/opt/app/static/
    networks:
      - app-net

volumes:
  pg_data:
  tg_bot_logs:
  static_volume:

networks:
  app-net:
    external: true
    name: app-net
